######################################################################
# Automatically generated by qmake (3.0) Wed Sep 16 07:49:45 2015
######################################################################

TEMPLATE = app
TARGET = filedialog
INCLUDEPATH += .

# Input
HEADERS += mydialog.h
SOURCES += main.cpp mydialog.cpp

LIBS += -framework QtWidgets

QMAKE_CXXFLAGS += -std=c++11 -stdlib=libc++